### ISSUE TITLE
Version Management for Asset Files

### ISSUE THREAD

**Issue by cqr** [PRX/www.radiotopia.fm#2]
https://git-annex.branchable.com/

This has been on my radar for a while but I haven't given it much attention yet. It might be worth looking into as our SOP for dealing with large assets in a git repository (i.e. setting up a submodule with an s3-special-remote or something similar).

Obviously we are able to manage this one manually for now, but there's a potential for this sort of need to start creeping into other projects and it would be useful to have a place to keep the discussion.

**Comment by kookster** [comment]
closing hold issus
