### ISSUE TITLE
Create donate button for Millennial

### ISSUE THREAD

**Issue by ginalooch** [PRX/www.radiotopia.fm#38]
create donate button to link to existing button located on: http://www.millennialpodcast.org/donate-help
first include this script within the HTML of the website:
`<script>`
(function() {
if(document.getElementById('commitchange-script')) return;
var npo = 4341;
var script = document.createElement('script');
var first = document.getElementsByTagName('script')[0];
script.setAttribute('data-npo-id', npo);
script.id = 'commitchange-script';
script.src = 'https://commitchange.com/js/donate-button.v2.js';
first.parentNode.insertBefore(script, first);
})();
`</script>`
 then add this snippet where the button should appear:
`<a` data-custom='' class='commitchange-donate donate' data-amounts='10,20,30,70,100,200,1000' `data-designation='Millennial'>Donate</a>`

This should allow the widget to hover on existing Donate Page.

**Comment by kookster** [comment]
n/a
